
version: '3.7'

volumes:
  db:

services:
  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: neos
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/data

